<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="colors.xacro"/>

    <link name="base_link"/>

    <link name="base_footprint">
    </link>

<!-- Create body -->
    <link name="body">
      <xacro:inertial_sphere mass="0.5" radius="${robot_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_sphere>
    </link>


<!-- Link for spherical joint z -->

    <link name="body_z">
      <visual>
        <geometry>
            <sphere radius="${robot_radius}"/>
        </geometry>
        <material name="blue"/>
      </visual>

      <collision name="body_z">
          <geometry>
              <cylinder radius="${robot_radius}" length="${2*robot_radius}"/>
          </geometry>
      </collision>

      <xacro:inertial_sphere mass="0.5" radius="${robot_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_sphere>
    </link>


    <!-- Gazebo references -->
    <gazebo reference="body_z">
      <material>Gazebo/Blue</material>
      <mu1>0.0</mu1>
      <mu2>0.0</mu2>
      <collision name="body_z">
        <surface>
          <friction>
            <ode>
              <mu>0</mu>
              <mu2>0</mu2>
            </ode>
            <torsional>
              <coefficient>0</coefficient>
              <use_patch_radius>false</use_patch_radius>
              <patch_radius>0.0</patch_radius>
            </torsional>
          </friction>
        </surface>
      </collision>
    </gazebo>

    <!-- Joint definitions -->
    <joint name="body_joint" type="fixed">
      <parent link="base_link"/>
      <child link="body"/>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <joint name="body_joint_z" type="continuous">
      <parent link="body"/>
      <child link="body_z"/>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 0 1"/>
    </joint>


    <joint name="footprint_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>


    <gazebo>
      <plugin name="gazebo_ros_joint_state_publisher"
          filename="libgazebo_ros_joint_state_publisher.so">
          <update_rate>20</update_rate>
          <joint_name>body_joint_z</joint_name>
      </plugin>
  </gazebo>

</robot>